config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  post 'sign_up', to: 'users#create'
  get 'sign_up', to: 'users#new'

  # Routes for account
  put 'account', to: 'users#update'
  get 'account', to: 'users#edit'
  delete 'account', to: 'users#destroy'

  # Routes for login
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'login', to: 'sessions#new'
  # Routes for sessions
  resources :active_sessions, only: [:destroy] do
    collection do
      delete 'destroy_all'
    end
  end

  # Routes form confirmations
  resources :confirmations, only: %i[create edit new], param: :confirmation_token

  # Routes for password
  resources :passwords, only: %i[create edit new update], param: :password_reset_token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  CONFIRMATION_TOKEN_EXPIRATION = 10.minutes
  MAILER_FROM_EMAIL = 'no-reply@example.com'
  PASSWORD_RESET_TOKEN_EXPIRATION = 10.minutes

  attr_accessor :current_password

  has_secure_password

  has_many :active_sessions, dependent: :destroy

  before_save :downcase_email
  before_save :downcase_unconfirmed_email

  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, presence: true, uniqueness: true
  validates :unconfirmed_email, format: { with: URI::MailTo::EMAIL_REGEXP, allow_blank: true }

  # @return [User, nil]
  def self.authenticate_by(attributes)
    passwords, identifiers = attributes.to_h.partition do |name, _value|
      !has_attribute?(name) && has_attribute?("#{name}_digest")
    end.map(&:to_h)

    raise ArgumentError, 'One or more password arguments are required' if passwords.empty?
    raise ArgumentError, 'One or more finder arguments are required' if identifiers.empty?

    record = find_by(identifiers)
    return nil unless record

    if passwords.count { |name, value| record.public_send(:"authenticate_#{name}", value) } == passwords.size
      record
    end
  end

  def confirm!
    return false unless unconfirmed_or_reconfirming?

    if update(email: unconfirmed_email, unconfirmed_email: nil, confirmed_at: Time.current)
      true
    else
      false
    end
  end

  def confirmed?
    confirmed_at.present?
  end

  def confirmable_email
    unconfirmed_email.presence || email
  end

  def generate_confirmation_token
    signed_id expires_in: CONFIRMATION_TOKEN_EXPIRATION, purpose: :confirm_email
  end

  def generate_password_reset_token
    signed_id expires_in: PASSWORD_RESET_TOKEN_EXPIRATION, purpose: :reset_password
  end

  def send_confirmation_email!
    confirmation_token = generate_confirmation_token
    UserMailer.confirmation(self, confirmation_token).deliver_now
  end

  def send_password_reset_email!
    password_reset_token = generate_password_reset_token
    UserMailer.password_reset(self, password_reset_token).deliver_now
  end

  def reconfirming?
    unconfirmed_email.present?
  end

  def unconfirmed?
    !confirmed?
  end

  def unconfirmed_or_reconfirming?
    unconfirmed? || reconfirming?
  end

  private

  def downcase_email
    self.email = email.downcase
  end

  def downcase_unconfirmed_email
    return if unconfirmed_email.nil?

    self.unconfirmed_email = unconfirmed_email.downcase
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!, only: %i[edit destroy update]
  before_action :redirect_if_authenticated, only: %i[create new]

  def create
    @user = User.new(create_user_params)
    if @user.save
      @user.send_confirmation_email!
      redirect_to root_path, notice: 'Please check your email for confirmation instructions.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    current_user.destroy
    reset_session
    redirect_to root_path, notice: 'Your account has been deleted.'
  end

  def edit
    @user = current_user
    @active_sessions = active_sessions
  end

  def new
    @user = User.new
  end

  def update
    @user = current_user
    if @user.authenticate(params[:user][:current_password])
      if @user.update(update_user_params)
        if params[:user][:unconfirmed_email].present?
          @user.send_confirmation_email!
          redirect_to root_path, notice: 'Check your email for confirmation instructions.'
        else
          redirect_to root_path, notice: 'Account updated.'
        end
      else
        render :edit, status: :unprocessable_entity
      end
    else
      flash.now[:error] = 'Incorrect password'
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def create_user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def update_user_params
    params.require(:user).permit(:current_password, :password, :password_confirmation, :unconfirmed_email)
  end

  def active_sessions
    current_user.active_sessions.order(created_at: :desc)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= form_with model: @user, url: account_path, method: :put do |form| %>
  <%= render partial: "shared/form_errors", locals: { object: form.object } %>
  <div>
    <%= form.label :email, "Current Email" %>
    <%= form.email_field :email, disabled: true %>
  </div>
  <div>
    <%= form.label :unconfirmed_email, "New Email" %>
    <%= form.text_field :unconfirmed_email %>
  </div>
  <div>
    <%= form.label :password, "Password (leave blank if you don't want to change it)" %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>
  <hr/>
  <div>
    <%= form.label :current_password, "Current password (we need your current password to confirm your changes)" %>
    <%= form.password_field :current_password, required: true %>
  </div>
  <%= form.submit "Update Account" %>
<% end %>

<h2>Current Logins</h2>
<% if @active_sessions.any? %>
  <%= button_to "Log out of all other sessions", destroy_all_active_sessions_path, method: :delete %>
  <table>
    <thead>
    <tr>
      <th>User Agent</th>
      <th>IP Address</th>
      <th>Signed In At</th>
      <th>Sign Out</th>
    </tr>
    </thead>
    <tbody>
    <%= render @active_sessions %>
    </tbody>
  </table>
<% end %>

app/views/users/new.html.erb
<div class="w-full max-w-ws">
  <%= form_with model: @user, url: sign_up_path, class: 'bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4' do |form| %>
    <%= render partial: "shared/form_errors", locals: { object: form.object } %>
    <div class="mb-4">
      <%= form.label :email, class: 'block text-gray-700 text-sm font-bold mb-2', for: 'email' %>
      <%= form.email_field :email, id: 'email', required: true, placeholder: 'email', class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
    </div>
    <div class="mb-6">
      <%= form.label :password, class: 'block text-gray-700 text-sm font-bold mb-2' %>
      <%= form.password_field :password, required: true, placeholder: 'password', class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
    </div>
    <div class="mb-8">
      <%= form.label :password_confirmation, class: 'block text-gray-700 text-sm font-bold mb-2' %>
      <%= form.password_field :password_confirmation, required: true, placeholder: 'password confirmation' , class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
    </div>
    <%= form.submit "Sign Up", class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full' %>
  <% end %>
</div>