config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  post 'sign_up', to: 'users#create'
  get 'sign_up', to: 'users#new'

  # Routes for account
  put 'account', to: 'users#update'
  get 'account', to: 'users#edit'
  delete 'account', to: 'users#destroy'

  # Routes for login
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'login', to: 'sessions#new'
  # Routes for sessions
  resources :active_sessions, only: [:destroy] do
    collection do
      delete 'destroy_all'
    end
  end

  # Routes form confirmations
  resources :confirmations, only: %i[create edit new], param: :confirmation_token

  # Routes for password
  resources :passwords, only: %i[create edit new update], param: :password_reset_token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
  <title>FirstLogin</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<header>
  <% flash.each do |message_type, message| %>
    <div class="<%= message_type %>"><%= message %></div>
  <% end %>
  <nav x-data="{ isOpen: false }" class="bg-white border-gray-200 dark:bg-gray-900">
    <div class='max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4'>
      <a href="https://github.com/zayko-dev" class="flex items-center">
        <%= image_tag "logo-dev.jpg", height: 100, width: 50, class: 'rounded-full border-4 border-white' %>
        <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Zayko-Dev</span>
      </a>
      <button @click="isOpen = !isOpen" x-show="!isOpen" data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
        <span class="sr-only">Open main menu</span>
        <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path>
        </svg>
      </button>
      <div x-show="isOpen" class="hidden w-full md:block md:w-auto" id="navbar-default">
        <ul class="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
          <% if user_signed_in? %>
            <li><%= link_to "My Account", account_path %></li>
            <li><%= button_to "Logout", logout_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Login", login_path, class: 'block py-2 pl-3 pr-4 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white md:dark:text-blue-500' %></li>
            <li><%= link_to "Sign Up", sign_up_path, class: 'block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent' %></li>
            <li><%= link_to "Forgot my password", new_password_path, class: 'block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent' %></li>
            <li><%= link_to "Didn't receive confirmation instructions", new_confirmation_path, class: 'block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent' %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>
<main class="container mx-auto mt-28 px-5 flex">
  <%= yield %>
</main>
</body>
</html>